// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdnzjihjukddihkvktxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbnpqaWhqdWtkZGloa3ZrdHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDgwMzQsImV4cCI6MjA2NzMyNDAzNH0.3tkqa6tvQu6zsELJZBYHCt6Ct8Ybj6RSsu3fsQ42TFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});